spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///novel_net
    username: root
    password: 123123

mybatis-plus:
  type-aliases-package: com.novelnet.demo.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  helper-dialect: mysql

server:
  port: 8081
  servlet:
    session:
      timeout: 86400